name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: g++ 11
      run: |
            sudo apt install gcc-10 g++-11
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
            sudo update-alternatives --set gcc /usr/bin/gcc-11
    - name: g++ version
      run: g++ --version
    - name: boost
      run: sudo apt install libboost-1.77
    - name: make rendor
      run: make -f Makefile.rendorc
    - name: make rendorc
      run: make -f Makefile.rendorc
