name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: GCC 11
      run: sudo apt install gcc-11 g++-11
    - name: Remove g++ link
      run: rm /usr/bin/g++
    - name: set g++ link
      run: ln -s /usr/bin/g++-11 /usr/bin/g++
    - name: g++ version
      run: g++ --version
    - name: boost
      run: sudo apt-get install -yq libboost-all-dev
    - name: make rendor
      run: make -f Makefile.rendorc
    - name: make rendorc
      run: make -f Makefile.rendorc
